services:

  db:
    image: nulltrace-db:latest
    build: ./database
    container_name: nulltrace-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nulltrace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nulltrace-net

  backend:
    image: nulltrace-backend:latest
    build: ./flask_backend
    container_name: nulltrace-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: nulltrace
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000"
    networks:
      - nulltrace-net

  frontend:
    image: nulltrace-frontend:latest
    build: ./frontend
    container_name: nulltrace-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000
    ports:
      - "3000:3000"
    networks:
      - nulltrace-net

volumes:
  postgres_data:

networks:
  nulltrace-net:
    driver: bridge